import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>Myntra-clone_By_Montu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/myntra.ico" />
      </Head>

    {/* Let's break The entire page into small components. */}

    <Header />

    {/* Slider */}

    </div>
  )
}
